apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-persistentvolume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  storageClassName: gcs-storage-class
  mountOptions:
    - implicit-dirs
    - file-cache:enable-parallel-downloads:true
    - file-cache:max-size-mb:-1
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: lookit-$(ENVIRONMENT)-private
  claimRef:
    name: gcs-fuse-csi-static-pvc
    namespace: default 