apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-gcs-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: $(CLUSTER_ISSUER)
    nginx.ingress.kubernetes.io/rewrite-target: "/lookit-$(ENVIRONMENT)/$1/$3"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: "storage.googleapis.com"
spec:
  ingressClassName: nginx
  rules:
    - host: $(SITE_DOMAIN)
      http:
        paths:
          - path: /(media|static)(/|$)(.*)
            pathType: Prefix
            # path: /(media|static)/(.*)
            backend:
              service:
                name: google-storage
                port: 
                  number: 443
    - host: $(SECONDARY_DOMAIN)
      http:
        paths:
          - path: /(media|static)(/|$)(.*)
            pathType: Prefix
            # path: /(media|static)/(.*)
            backend:
              service:
                name: google-storage
                port: 
                  number: 443
  tls:
    - hosts:
      - $(SITE_DOMAIN)
      - $(SECONDARY_DOMAIN)
      secretName: lookit-cert