apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: $(CLUSTER_ISSUER)
spec:
  rules:
  - host: $(SITE_DOMAIN)
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: http
      - path: /*
        backend:
          serviceName: web
          servicePort: http
  tls:
  - hosts:
    - $(SITE_DOMAIN)
    secretName: lookit-cert