apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  annotations:
    lookit-env-vars: "injected"
    wait-for-gcloud-sqlproxy: "true"
    wait-for-rabbitmq: "true"
spec:
  selector:
    matchLabels: {}
  template:
    spec:
      initContainers: []
      containers:
      - name: worker
        image: lookit
        imagePullPolicy: IfNotPresent
        command:
        - gosu
        - www-data
        - celery
        - -A
        - project.celery.app
        - worker
        - -c
        - "1"
        - -l
        - INFO
        - -n
        - worker.%h
        - --without-gossip
        - --max-tasks-per-child
        - "5"
        - -Q
        - email
        env: []
        volumeMounts:
        - mountPath: /etc/googleAppCreds.json
          name: secret-volume
          readOnly: true
          subPath: googleAppCreds.json
      volumes:
      - name: config-volume
        configMap:
          defaultMode: 420
          name: lookit-configmap
      - name: secret-volume
        secret:
          defaultMode: 420
          secretName: lookit-secrets
      - name: cloudsql-instance-credentials
        secret:
          defaultMode: 420
          secretName: cloudsql-instance-credentials
